In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('D:/ml/marketing_campaign.csv',sep=';')
df.head()

ID  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0  5524        1957  Graduation         Single  58138.0        0         0   
1  2174        1954  Graduation         Single  46344.0        1         1   
2  4141        1965  Graduation       Together  71613.0        0         0   
3  6182        1984  Graduation       Together  26646.0        1         0   
4  5324        1981         PhD        Married  58293.0        1         0   

  Dt_Customer  Recency  MntWines  ...  NumWebVisitsMonth  AcceptedCmp3  \
0  2012-09-04       58       635  ...                  7             0   
1  2014-03-08       38        11  ...                  5             0   
2  2013-08-21       26       426  ...                  4             0   
3  2014-02-10       26        11  ...                  6             0   
4  2014-01-19       94       173  ...                  5             0   

   AcceptedCmp4  AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  Complain  \
0             0             0             0             0         0   
1             0             0             0             0         0   
2             0             0             0             0         0   
3             0             0             0             0         0   
4             0             0             0             0         0   

   Z_CostContact  Z_Revenue  Response  
0              3         11         1  
1              3         11         0  
2              3         11         0  
3              3         11         0  
4              3         11         0  

[5 rows x 29 columns]

In [3]:
# Mnt = Amount spend on product
# Acceptcmp = the funds raised to promote product

In [4]:
df.columns

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response'],
      dtype='object')

In [5]:
df.Response.value_counts()

0    1906
1     334
Name: Response, dtype: int64

In [6]:
df.drop(['Z_CostContact','Z_Revenue'],axis=1,inplace=True)

In [7]:
df.drop('Dt_Customer',axis=1,inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   ID                   2240 non-null   int64  
 1   Year_Birth           2240 non-null   int64  
 2   Education            2240 non-null   object 
 3   Marital_Status       2240 non-null   object 
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64  
 6   Teenhome             2240 non-null   int64  
 7   Recency              2240 non-null   int64  
 8   MntWines             2240 non-null   int64  
 9   MntFruits            2240 non-null   int64  
 10  MntMeatProducts      2240 non-null   int64  
 11  MntFishProducts      2240 non-null   int64  
 12  MntSweetProducts     2240 non-null   int64  
 13  MntGoldProds         2240 non-null   int64  
 14  NumDealsPurchases    2240 non-null   int64  
 15  NumWebPurchases      2240 non-null   i

In [9]:
df.describe()

ID   Year_Birth         Income      Kidhome     Teenhome  \
count   2240.000000  2240.000000    2216.000000  2240.000000  2240.000000   
mean    5592.159821  1968.805804   52247.251354     0.444196     0.506250   
std     3246.662198    11.984069   25173.076661     0.538398     0.544538   
min        0.000000  1893.000000    1730.000000     0.000000     0.000000   
25%     2828.250000  1959.000000   35303.000000     0.000000     0.000000   
50%     5458.500000  1970.000000   51381.500000     0.000000     0.000000   
75%     8427.750000  1977.000000   68522.000000     1.000000     1.000000   
max    11191.000000  1996.000000  666666.000000     2.000000     2.000000   

           Recency     MntWines    MntFruits  MntMeatProducts  \
count  2240.000000  2240.000000  2240.000000      2240.000000   
mean     49.109375   303.935714    26.302232       166.950000   
std      28.962453   336.597393    39.773434       225.715373   
min       0.000000     0.000000     0.000000         0.000000   
25%      24.000000    23.750000     1.000000        16.000000   
50%      49.000000   173.500000     8.000000        67.000000   
75%      74.000000   504.250000    33.000000       232.000000   
max      99.000000  1493.000000   199.000000      1725.000000   

       MntFishProducts  ...  NumCatalogPurchases  NumStorePurchases  \
count      2240.000000  ...          2240.000000        2240.000000   
mean         37.525446  ...             2.662054           5.790179   
std          54.628979  ...             2.923101           3.250958   
min           0.000000  ...             0.000000           0.000000   
25%           3.000000  ...             0.000000           3.000000   
50%          12.000000  ...             2.000000           5.000000   
75%          50.000000  ...             4.000000           8.000000   
max         259.000000  ...            28.000000          13.000000   

       NumWebVisitsMonth  AcceptedCmp3  AcceptedCmp4  AcceptedCmp5  \
count        2240.000000   2240.000000   2240.000000   2240.000000   
mean            5.316518      0.072768      0.074554      0.072768   
std             2.426645      0.259813      0.262728      0.259813   
min             0.000000      0.000000      0.000000      0.000000   
25%             3.000000      0.000000      0.000000      0.000000   
50%             6.000000      0.000000      0.000000      0.000000   
75%             7.000000      0.000000      0.000000      0.000000   
max            20.000000      1.000000      1.000000      1.000000   

       AcceptedCmp1  AcceptedCmp2     Complain     Response  
count   2240.000000   2240.000000  2240.000000  2240.000000  
mean       0.064286      0.013393     0.009375     0.149107  
std        0.245316      0.114976     0.096391     0.356274  
min        0.000000      0.000000     0.000000     0.000000  
25%        0.000000      0.000000     0.000000     0.000000  
50%        0.000000      0.000000     0.000000     0.000000  
75%        0.000000      0.000000     0.000000     0.000000  
max        1.000000      1.000000     1.000000     1.000000  

[8 rows x 24 columns]

In [10]:
df['Age']=2014-df['Year_Birth']

In [11]:
df['Education'].unique()

array(['Graduation', 'PhD', 'Master', 'Basic', '2n Cycle'], dtype=object)

In [12]:
df['Education']=df['Education'].map({'Graduation':'UG','PhD':'PG','Master':'PG','Basic':'10th','2n Cycle':'PU'})

In [13]:
df['Marital_Status']=df['Marital_Status'].map({'Single':'1','Together':'0','Married':'0','Divorced':'1','Widow':'1','Alone':'1','Absurd':'1','YOLO':'1'})

In [14]:
df['Marital_Status']=df['Marital_Status'].apply(np.int64)

In [15]:
df['Marital_Status'].unique()

array([1, 0], dtype=int64)

In [16]:
df['Income']=df['Income'].fillna(df['Income'].mean())

In [17]:
df['toal_children']=df['Kidhome']+df['Teenhome']

In [18]:
df.columns

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Recency', 'MntWines', 'MntFruits', 'MntMeatProducts',
       'MntFishProducts', 'MntSweetProducts', 'MntGoldProds',
       'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases',
       'NumStorePurchases', 'NumWebVisitsMonth', 'AcceptedCmp3',
       'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1', 'AcceptedCmp2',
       'Complain', 'Response', 'Age', 'toal_children'],
      dtype='object')

In [19]:
df['total spend']=df['MntWines']+df['MntFruits']+df['MntMeatProducts']+df['MntFishProducts']+df['MntSweetProducts']+df['MntGoldProds']

In [20]:
df['total purchase']=df['NumDealsPurchases']+df['NumWebPurchases']+df['NumCatalogPurchases']+df['NumStorePurchases']+df['NumWebVisitsMonth']

In [21]:
df['total AcceptedCmp']=df['AcceptedCmp5']+df['AcceptedCmp4']+df['AcceptedCmp3']+df['AcceptedCmp2']+df['AcceptedCmp1']

In [22]:
c=df['Recency'].sort_values()
#c=list(c)
q1=c.quantile(0.25)
q2=c.quantile(0.75)
q1,q2

(24.0, 74.0)

In [23]:
a=[]
for i in df['Recency']:
    if i<24:
        a.append('normal customer')
    elif i>74:
        a.append('special customer')
    else:
        a.append('good customer')
len(a)

2240

In [24]:
df['customer_catagory']=a

In [25]:
df['total kids']=df['Kidhome']+df['Teenhome']

In [26]:
df.columns

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Recency', 'MntWines', 'MntFruits', 'MntMeatProducts',
       'MntFishProducts', 'MntSweetProducts', 'MntGoldProds',
       'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases',
       'NumStorePurchases', 'NumWebVisitsMonth', 'AcceptedCmp3',
       'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1', 'AcceptedCmp2',
       'Complain', 'Response', 'Age', 'toal_children', 'total spend',
       'total purchase', 'total AcceptedCmp', 'customer_catagory',
       'total kids'],
      dtype='object')

In [27]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Education']=le.fit_transform(df['Education'])

In [28]:
df['customer_catagory']=le.fit_transform(df['customer_catagory'])

In [29]:
df1=df[['Education','Marital_Status', 'Income','Complain', 'Age', 'total spend', 'total purchase',
       'total AcceptedCmp', 'Recency', 'total kids']]

In [30]:
#df1['Education']=df1['Education'].strip()

In [31]:
df['total kids'].unique()

array([0, 2, 1, 3], dtype=int64)

In [32]:
df.Complain.dtype

dtype('int64')

In [33]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
df1=ss.fit_transform(df1)

In [34]:
import scipy.cluster.hierarchy as sch 
from sklearn.cluster import AgglomerativeClustering
from matplotlib import pyplot as plt
import seaborn as sns

In [35]:
#dendrogram = sch.dendrogram(sch.linkage(df1, method='complete'))

In [36]:
hc = AgglomerativeClustering(n_clusters=9, affinity = 'euclidean', linkage = 'complete')

In [37]:
model=hc.fit(df1)

In [38]:
y_hc=hc.fit_predict(df1)
y_hc

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)